from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT


def generate_docstring(file_str, fn_name):
    anthropic = Anthropic(
        # defaults to os.environ.get("ANTHROPIC_API_KEY")
        api_key="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",
    )

    prompt_file = open("resources/prompt.txt", "r")
    prompt = prompt_file.read()
    prompt = prompt.replace("[fn_name]", fn_name)
    prompt = prompt.replace("[file]", file_str)

    # TODO: replace this default dostring template with one generated by Claude
    # (so it can support any language, not just Python)
    template_file = open("resources/python_docstring_template.txt", "r")
    docstring_template = template_file.read()
    prompt = prompt.replace("[docstring_example]", docstring_template)

    completion = anthropic.completions.create(
        model="claude-2",
        max_tokens_to_sample=300,
        prompt=prompt,
    )
    print(completion.completion)


if __name__ == "__main__":
    file = open("sampleFile.txt", "r")
    content = file.read()
    generate_docstring(content, "one_hot")
