from openai import OpenAI
client = OpenAI(
    api_key="Add key"
)

with open("../test_scripts/demo3.py", "r") as f:
        content = f.read()

prompt_file = open("../resources/prompt.txt", "r")
prompt = prompt_file.read()
prompt = prompt.replace("[fn_name]", "add_docstring")
prompt = prompt.replace("[file]", content)

    # TODO: replace this default docstring template with one generated by Claude?
    # (so it can support any language, not just Python)
template_file = open("../resources/templates/function_templates/python_template.txt", "r")
docstring_template = template_file.read()
prompt = prompt.replace("[docstring_example]", docstring_template)


completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
      {"role": "system", "content": prompt}
  ]
)

print(completion.choices[0].message.content)


